"(define (cstr str)\n"
"  (define (rec str ch k is-nl?)\n"
"    (if is-nl? (display \"\\\"\"))\n"
"    (cond ((= k (string-length str))\n"
"           (display \"\\\"\"))\n"
"          ((char=? ch #\\newline)\n"
"           (display \"\\\\n\\\"\\n\")\n"
"           (rec str (string-ref str k) (+ k 1) #t))\n"
"          ((char=? ch #\\\")\n"
"           (display \"\\\\\\\"\")\n"
"           (rec str (string-ref str k) (+ k 1) #f))\n"
"          ((char=? ch #\\\\)\n"
"           (display \"\\\\\\\\\")\n"
"           (rec str (string-ref str k) (+ k 1) #f))\n"
"          (else\n"
"           (display ch)\n"
"           (rec str (string-ref str k) (+ k 1) #f))))\n"
"  (rec str (string-ref str 0) 1 #t))"
