"(define (cstr str)\n"
"  (define (strify ch)\n"
"    (cond ((char=? ch #\\newline)\n"
"           \"\\\\n\\\"\\n\\\"\")\n"
"          ((char=? ch #\\\")\n"
"            \"\\\\\\\"\")\n"
"          ((char=? ch #\\\\)\n"
"           \"\\\\\\\\\")\n"
"          (else\n"
"           (make-string 1 ch))))\n"
"\n"
"  (define (rec ch k acc)\n"
"    (cond ((>= k (string-length str))\n"
"           (string-append acc (strify ch) \"\\\"\"))\n"
"          (else\n"
"           (rec (string-ref str k)\n"
"                (+ k 1)\n"
"                (string-append acc (strify ch))))))\n"
"\n"
"  (rec (string-ref str 0) 1 \"\\\"\"))"
